captcha:
  key-long: 4
  img-width: 120
  img-height: 40
casbin:
  model-path: ./resource/rbac_model.conf
cron:
  spec_all: 0 23 * * ?
jwt:
  signing-key: qmPlus
log:
  prefix: '[Taylors-LOG]'
  log-file: true
  stdout: DEBUG
  file: DEBUG
crawler:
  url: "http://24.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=5000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m:0+t:6,m:0+t:13,m:0+t:80,m:1+t:2,m:1+t:23&fields=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f12,f13,f14,f15,f16,f17,f18,f20,f21,f23,f24,f25,f22,f11,f62,f128,f136,f115,f152&_=1590799480841"
  env: "dev"
  sleep: 30
mysql:
  username: root
  password: password
  path: 192.168.243.131:3306
  db-name: taylors
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true
qiniu:
  access-key: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
  bucket: qm-plus-img
  img-path: http://qmplusimg.henrongyi.top
redis:
  addr: 192.168.1.97:6379
  password: ""
  db: 0
sqlite:
  username: ""
  password: ""
  path: db.db
  config: loc=Asia/Shanghai
  log-mode: true
system:
  use-multipoint: false
  env: public
  addr: 9999
  db-type: mysql
